version: '3'
services:
  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - '5000:5000'
  client:
    stdin_open: true
    build: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'
    depends_on:
      - api